### ISSUE TITLE
Contract. Replace ticker with name

### ISSUE THREAD

**Issue by AndreKuren** [Tsunami-Exchange/tsunami-contracts#27]
Я, как трейдер, при осуществлении поиска и визуального просмотра списка активов, должен видеть не только тикер токена но и наименование проекта. Отображение в перечне активов наименования проекта к которому относится тикер, позволит мне лучше ориентироваться в доступных активах и осуществлять более гибкий поиск.
Необходимо на контракте помимо тикера добавить наименования проекта к которому относится токен, там где это актуально. Из текущего списка активов:
DOT - Polkadot
BNB - Binance coin
LTC - Litecoin
BTC - Bitcoin
ETH - Ethereum

**Comment by AndreKuren** [comment]
@execc вижу изменения в координаторе на devnet: https://testnet.wavesexplorer.com/address/3MzdomR4UkWKtVXq6YGouPJsYXDunjCvSJ8/data
Необходимо добавить на пром: https://classic.wavesexplorer.com/address/3PPZ8hSuQuVNMw2AFWAidopQGVMqCujB13Z/data

А так же, на проме заменить tags "Waves Ecosystem" на "Layer 1" для DOT \ BNB \ LTC \ BTC \ ETH

**Comment by execc** [comment]
Сделано. Можно проверять на ПРОМЕ.

**Comment by AndreKuren** [comment]
Test done.
