### ISSUE TITLE
Contract. Funding in the absence of counter positions

### ISSUE THREAD

**Issue by AndreKuren** [Tsunami-Exchange/tsunami-contracts#28]
На рынке иногда скрадывается ситуация, когда открыты позиции только в лонг или шорт. При отсутствии контр позиции у нас перестает рассчитываться и взиматься фандинг.
Необходимо внести изменения в смарт контракты, с тем, чтобы у нас рассчитывался и снимался фандинг, даже в том случае, если на одной стороне объем открытой позиции равен 0. При этом кейсе весь собираемый фандинг поступает в Vault для распределения между LP.

**Comment by execc** [comment]
Разработал, задеплоил на ДЕВ. Можно тестить.

**Comment by AndreKuren** [comment]
Test done.

![Image](https://github.com/Tsunami-Exchange/tsunami-contracts/assets/49484901/d9165da6-c0ce-4500-b4e6-a73c0a515c9b)
