### ISSUE TITLE
Contract. Fix base asset for DOT

### ISSUE THREAD

**Issue by AndreKuren** [Tsunami-Exchange/tsunami-contracts#31]
В координаторе некорректно указан baseAsset для DOT. Сейчас там ETH, необходимо изменить на DOT.

Сейчас так: 
```
 {
    "key": "k_amm_data_3PFdikCQhWCWYGhBxXSuBhmQXBGKFRxR9Zt",
    "type": "string",
    "value": "{ \"imageLink\": \"https://devnet.tsunami.exchange/markets/dot.png\", \"quoteAsset\": \"USDX\", \"baseAsset\": \"ETH\", \"name\": \"DOT\", \"ticker\": \"DOTUSDX\", \"tags\": [\"Waves Ecosystem\",\"USDX\"]  }"
  }
```

**Comment by execc** [comment]
Done!

**Comment by AndreKuren** [comment]
@execc на проме всё так же, указано  "value": "{ \"imageLink\": \"https://devnet.tsunami.exchange/markets/dot.png\", \"quoteAsset\": \"USDX\", \"baseAsset\": \"ETH\", \"name\": \"Polkadot\", \"ticker\": \"DOT/USDX\", \"tags\": [\"Layer 1\",\"USDX\"]  }"

**Comment by AndreKuren** [comment]
Изменен на {
    "key": "k_amm_data_3PFdikCQhWCWYGhBxXSuBhmQXBGKFRxR9Zt",
    "type": "string",
    "value": "{ \"imageLink\": \"https://devnet.tsunami.exchange/markets/dot.png\", \"quoteAsset\": \"USDX\", \"baseAsset\": \"DOT\", \"name\": \"DOT\", \"ticker\": \"DOTUSDX\", \"tags\": [\"Waves Ecosystem\",\"USDX\"]  }"
  }

Теперь корреткный baseAsset, но некорреткный name и tags, исправляем в рамках другого тикета.
